### PR TITLE
Allow data to be passed to the modal

### PR DESCRIPTION
**Pull request by li0nza**

### CODE REVIEW

**Comment by pglazkov** [comment]
Thanks for your contribution! However, I'm not completely sure if this change is needed to accomplish the task of passing data to the modal component. There is already a way to do it via `modalRef.componentInstance` as shown here: https://github.com/Independer/ng-modal/blob/634bb08453c67a67de211f16eb88151bf0af25c0/playground/src/app/home.component.ts#L16

What would be the advantage of passing the data into the `open` call instead?

**Comment by li0nza** [comment]
It just feels disconnected from the modal to be honest.  I actually saw that you could pass the data like that when I was about 90% done with the update, and thought I might as well finish it and push it.

Also, not sure if this is the right place to ask, but is there a way to pass a CSS class to add to the modal, in particular to the modal-dialog div?

**Comment by davidwalschots** [comment]
@li0nza I can understand you feel it's disconnected a bit. I'm not sure if I like the way you provide injected data now. I'd propose the following as an alternative:

```ts
open<T>(componentType: Type<T>, initialise?: (instance: T) => void): ModalRef<T> {
```

```ts
const modalRef = this.modalService.open(ModalComponent, modal => {
  modal.data = 'Modal initialization data set from HomeComponent';
  modal.otherProperty = 123;
  // etc.
});
```

@pglazkov any thoughts on this?

**Comment by li0nza** [comment]
Actually didn't think of doing it like that, but that makes a lot of sense.

**Comment by pglazkov** [comment]
I like the approach proposed by @davidwalschots. It is flexible and addresses the issue. @li0nza, would you like to implement it?

Regarding the question about adding a CSS class, it is not possible at this moment, however, you should be able to achieve what you want by using `::ng-deep` selector to target `modal-content` class:

```css
.bold-content {
  ::ng-deep .modal-content {
    font-weight: bold;
  }
}
```

```html
<modal class="bold-content">
  <modal-content>
     ...
  </modal-content>
</modal>
```

**Comment by li0nza** [comment]
@pglazkov sure, I will get to it tonight and update the PR.  Thanks for the suggestion on the CSS.

**Comment by davidwalschots** [comment]
I'm missing the call to the `initialise` function; and not all the previous changes have been cleaned up in this commit.

**Pull request merged**
